"""State management for the interview coach."""
from state.schema import (
    CANDIDATE_ROLE,
    CANDIDATE_BACKGROUND,
    FOCUS_AREA,
    SESSION_STRATEGY,
    CONVERSATION_HISTORY,
    TURN_SCORES,
    LAST_EVALUATOR_SIGNAL,
    CURRENT_TURN,
    INTERVIEW_COMPLETE,
    COACHING_REPORT,
    initialize_state,
    append_turn_score,
    get_last_signal,
    increment_turn,
    mark_interview_complete,
    is_interview_complete,
    add_conversation_turn,
)

__all__ = [
    "CANDIDATE_ROLE",
    "CANDIDATE_BACKGROUND",
    "FOCUS_AREA",
    "SESSION_STRATEGY",
    "CONVERSATION_HISTORY",
    "TURN_SCORES",
    "LAST_EVALUATOR_SIGNAL",
    "CURRENT_TURN",
    "INTERVIEW_COMPLETE",
    "COACHING_REPORT",
    "initialize_state",
    "append_turn_score",
    "get_last_signal",
    "increment_turn",
    "mark_interview_complete",
    "is_interview_complete",
    "add_conversation_turn",
]
